### PR TITLE
#1 

### PR DESCRIPTION
**Pull request by CyberSarvesh**
--make the basic backend setup for the project
--made basic CRUD API
--made two schemas (User and Blog)
--used mongoDB for database

### CODE REVIEW

**Comment by pranshu05** [comment]
give @CyberSarvesh 50 points

**Comment by pranshu05** [comment]
@Trisha-tech I've given points to @CyberSarvesh, if any PR gets merged do give points to them, or ping me

**Comment by pranshu05** [comment]
@Trisha-tech pls give 50 points to @CyberSarvesh 

the format of the message should be `give @CyberSarvesh 50 points`

**Comment by Trisha-tech** [comment]
> --make the basic backend setup for the project --made basic CRUD API --made two schemas (User and Blog) --used mongoDB for database

give @CyberSarvesh 50 points

**Comment by pranshu05** [comment]
give @CyberSarvesh 50 points

**Comment by pranshu05** [comment]
Sorry there was some issue in the backend

**Pull request merged**
